#!/usr/bin/env python3
"""
AI BUILDER - User-Friendly Specialized AI Creation Tool
Cross-platform (Linux & Windows) AI model builder

By: Vulcan (The Forge)
For: Anthony Eric Chavez - The Keeper
Signature: VULCAN-THE-FORGE-2025
"""

import os
import sys
import json
import platform
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any

# ============================================================================
# CONFIGURATION
# ============================================================================

KEEPERS_ROOM = os.path.dirname(os.path.abspath(__file__))
AI_MODELS_DIR = os.path.join(KEEPERS_ROOM, "ai_models")
TEMPLATES_DIR = os.path.join(KEEPERS_ROOM, "ai_templates")
CONFIG_FILE = os.path.join(KEEPERS_ROOM, "ai_builder_config.json")

# ============================================================================
# AI BUILDER CLASS
# ============================================================================

class AIBuilder:
    """User-Friendly AI Builder - Cross-Platform"""

    def __init__(self):
        self.system = platform.system()
        self.python_cmd = "python3" if self.system != "Windows" else "python"
        self.setup_directories()
        self.load_config()

    def setup_directories(self):
        """Setup required directories"""
        os.makedirs(AI_MODELS_DIR, exist_ok=True)
        os.makedirs(TEMPLATES_DIR, exist_ok=True)
        self.create_templates()

    def load_config(self):
        """Load configuration"""
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r') as f:
                self.config = json.load(f)
        else:
            self.config = {
                "default_framework": "tensorflow",
                "default_language": "python",
                "models_created": 0
            }
            self.save_config()

    def save_config(self):
        """Save configuration"""
        with open(CONFIG_FILE, 'w') as f:
            json.dump(self.config, f, indent=2)

    def create_templates(self):
        """Create AI templates"""
        templates = {
            "text_classifier": self.get_text_classifier_template(),
            "image_classifier": self.get_image_classifier_template(),
            "chatbot": self.get_chatbot_template(),
            "predictor": self.get_predictor_template(),
            "custom": self.get_custom_template()
        }

        for name, template in templates.items():
            template_path = os.path.join(TEMPLATES_DIR, f"{name}.py")
            if not os.path.exists(template_path):
                with open(template_path, 'w') as f:
                    f.write(template)

    def get_text_classifier_template(self):
        """Text classifier template"""
        return '''"""
Text Classifier AI Model
Generated by AI Builder
"""

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import pickle
import os

class TextClassifier:
    """Text Classification AI Model"""

    def __init__(self):
        self.model = Pipeline([
            ('tfidf', TfidfVectorizer()),
            ('classifier', MultinomialNB())
        ])
        self.trained = False

    def train(self, texts, labels):
        """Train the model"""
        print("Training text classifier...")
        self.model.fit(texts, labels)
        self.trained = True
        print("Training complete!")

    def predict(self, text):
        """Predict class for text"""
        if not self.trained:
            raise ValueError("Model not trained yet!")
        return self.model.predict([text])[0]

    def predict_proba(self, text):
        """Get prediction probabilities"""
        if not self.trained:
            raise ValueError("Model not trained yet!")
        return self.model.predict_proba([text])[0]

    def save(self, filepath):
        """Save model"""
        with open(filepath, 'wb') as f:
            pickle.dump(self.model, f)
        print(f"Model saved to {filepath}")

    def load(self, filepath):
        """Load model"""
        with open(filepath, 'rb') as f:
            self.model = pickle.load(f)
        self.trained = True
        print(f"Model loaded from {filepath}")

# Example usage
if __name__ == "__main__":
    # Create model
    model = TextClassifier()

    # Example training data
    texts = [
        "I love this product",
        "This is terrible",
        "Great service",
        "Poor quality"
    ]
    labels = ["positive", "negative", "positive", "negative"]

    # Train
    model.train(texts, labels)

    # Test
    test_text = "This is amazing!"
    prediction = model.predict(test_text)
    print(f"Prediction: {prediction}")

    # Save
    model.save("text_classifier_model.pkl")
'''

    def get_image_classifier_template(self):
        """Image classifier template"""
        return '''"""
Image Classifier AI Model
Generated by AI Builder
Requires: pip install tensorflow pillow numpy
"""

try:
    import tensorflow as tf
    from tensorflow import keras
    from PIL import Image
    import numpy as np
    HAS_TENSORFLOW = True
except ImportError:
    HAS_TENSORFLOW = False
    print("Warning: TensorFlow not installed. Install with: pip install tensorflow")

class ImageClassifier:
    """Image Classification AI Model"""

    def __init__(self, num_classes=10, input_shape=(224, 224, 3)):
        if not HAS_TENSORFLOW:
            raise ImportError("TensorFlow required. Install with: pip install tensorflow")

        self.num_classes = num_classes
        self.input_shape = input_shape
        self.model = None
        self.trained = False

    def build_model(self):
        """Build the model architecture"""
        self.model = keras.Sequential([
            keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=self.input_shape),
            keras.layers.MaxPooling2D(2, 2),
            keras.layers.Conv2D(64, (3, 3), activation='relu'),
            keras.layers.MaxPooling2D(2, 2),
            keras.layers.Conv2D(64, (3, 3), activation='relu'),
            keras.layers.Flatten(),
            keras.layers.Dense(64, activation='relu'),
            keras.layers.Dense(self.num_classes, activation='softmax')
        ])

        self.model.compile(
            optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
        )
        print("Model built successfully!")

    def train(self, images, labels, epochs=10, batch_size=32):
        """Train the model"""
        if self.model is None:
            self.build_model()

        print(f"Training for {epochs} epochs...")
        self.model.fit(images, labels, epochs=epochs, batch_size=batch_size)
        self.trained = True
        print("Training complete!")

    def predict(self, image):
        """Predict class for image"""
        if not self.trained:
            raise ValueError("Model not trained yet!")

        if isinstance(image, str):
            img = Image.open(image)
            img = img.resize(self.input_shape[:2])
            img = np.array(img) / 255.0
            img = np.expand_dims(img, axis=0)
        else:
            img = image

        prediction = self.model.predict(img)
        return np.argmax(prediction[0])

    def save(self, filepath):
        """Save model"""
        if self.model is None:
            raise ValueError("No model to save!")
        self.model.save(filepath)
        print(f"Model saved to {filepath}")

    def load(self, filepath):
        """Load model"""
        self.model = keras.models.load_model(filepath)
        self.trained = True
        print(f"Model loaded from {filepath}")

# Example usage
if __name__ == "__main__":
    if HAS_TENSORFLOW:
        model = ImageClassifier(num_classes=10)
        model.build_model()
        print("Image classifier model created!")
        print("Add your training data to train the model.")
    else:
        print("Install TensorFlow: pip install tensorflow")
'''

    def get_chatbot_template(self):
        """Chatbot template"""
        return '''"""
Chatbot AI Model
Generated by AI Builder
"""

import json
import random
from typing import Dict, List

class Chatbot:
    """Simple Chatbot AI Model"""

    def __init__(self):
        self.responses = {}
        self.context = {}
        self.trained = False

    def train(self, training_data: Dict[str, List[str]]):
        """Train chatbot with responses"""
        self.responses = training_data
        self.trained = True
        print("Chatbot trained!")

    def train_from_file(self, filepath: str):
        """Train from JSON file"""
        with open(filepath, 'r') as f:
            data = json.load(f)
        self.train(data)

    def respond(self, user_input: str) -> str:
        """Generate response"""
        if not self.trained:
            return "I'm not trained yet. Please train me first!"

        user_input_lower = user_input.lower()

        # Check for exact matches
        for key, responses in self.responses.items():
            if key.lower() in user_input_lower:
                return random.choice(responses)

        # Default response
        return "I'm not sure how to respond to that. Can you rephrase?"

    def add_response(self, keyword: str, response: str):
        """Add a response"""
        if keyword not in self.responses:
            self.responses[keyword] = []
        self.responses[keyword].append(response)

    def save(self, filepath: str):
        """Save chatbot"""
        with open(filepath, 'w') as f:
            json.dump(self.responses, f, indent=2)
        print(f"Chatbot saved to {filepath}")

    def load(self, filepath: str):
        """Load chatbot"""
        with open(filepath, 'r') as f:
            self.responses = json.load(f)
        self.trained = True
        print(f"Chatbot loaded from {filepath}")

# Example usage
if __name__ == "__main__":
    chatbot = Chatbot()

    # Training data
    training_data = {
        "hello": ["Hi there!", "Hello!", "Hey!"],
        "how are you": ["I'm doing well!", "Great, thanks!", "Pretty good!"],
        "goodbye": ["See you later!", "Bye!", "Take care!"]
    }

    chatbot.train(training_data)

    # Test
    print(chatbot.respond("Hello"))
    print(chatbot.respond("How are you?"))

    # Save
    chatbot.save("chatbot_model.json")
'''

    def get_predictor_template(self):
        """Predictor template"""
        return '''"""
Predictor AI Model
Generated by AI Builder
"""

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import pickle

class Predictor:
    """Prediction AI Model"""

    def __init__(self, model_type="linear"):
        self.model_type = model_type
        self.model = None
        self.trained = False

    def build_model(self):
        """Build the model"""
        if self.model_type == "linear":
            self.model = LinearRegression()
        elif self.model_type == "random_forest":
            self.model = RandomForestRegressor()
        else:
            raise ValueError(f"Unknown model type: {self.model_type}")
        print(f"{self.model_type} model created!")

    def train(self, X, y):
        """Train the model"""
        if self.model is None:
            self.build_model()

        print("Training predictor...")
        self.model.fit(X, y)
        self.trained = True
        print("Training complete!")

    def predict(self, X):
        """Make predictions"""
        if not self.trained:
            raise ValueError("Model not trained yet!")
        return self.model.predict(X)

    def score(self, X, y):
        """Get model score"""
        if not self.trained:
            raise ValueError("Model not trained yet!")
        return self.model.score(X, y)

    def save(self, filepath):
        """Save model"""
        with open(filepath, 'wb') as f:
            pickle.dump(self.model, f)
        print(f"Model saved to {filepath}")

    def load(self, filepath):
        """Load model"""
        with open(filepath, 'rb') as f:
            self.model = pickle.load(f)
        self.trained = True
        print(f"Model loaded from {filepath}")

# Example usage
if __name__ == "__main__":
    # Create model
    model = Predictor(model_type="linear")

    # Example training data
    X = np.array([[1], [2], [3], [4], [5]])
    y = np.array([2, 4, 6, 8, 10])

    # Train
    model.train(X, y)

    # Predict
    test_X = np.array([[6], [7], [8]])
    predictions = model.predict(test_X)
    print(f"Predictions: {predictions}")

    # Save
    model.save("predictor_model.pkl")
'''

    def get_custom_template(self):
        """Custom template"""
        return '''"""
Custom AI Model
Generated by AI Builder
Customize this template for your specific needs
"""

class CustomAI:
    """Custom AI Model - Customize as needed"""

    def __init__(self):
        self.trained = False
        # Add your initialization code here

    def train(self, data):
        """Train the model"""
        # Add your training code here
        self.trained = True
        print("Training complete!")

    def predict(self, input_data):
        """Make predictions"""
        if not self.trained:
            raise ValueError("Model not trained yet!")
        # Add your prediction code here
        return None

    def save(self, filepath):
        """Save model"""
        # Add your save code here
        print(f"Model saved to {filepath}")

    def load(self, filepath):
        """Load model"""
        # Add your load code here
        self.trained = True
        print(f"Model loaded from {filepath}")

# Example usage
if __name__ == "__main__":
    model = CustomAI()
    print("Custom AI model created!")
    print("Customize this template for your specific needs.")
'''

    def show_menu(self):
        """Show main menu"""
        print("\n" + "="*60)
        print("AI BUILDER - Specialized AI Creation Tool")
        print("="*60)
        print("")
        print("By: Vulcan (The Forge)")
        print("For: Anthony Eric Chavez - The Keeper")
        print("Signature: VULCAN-THE-FORGE-2025")
        print("")
        print("Platform:", self.system)
        print("")
        print("Options:")
        print("  1. Create Text Classifier")
        print("  2. Create Image Classifier")
        print("  3. Create Chatbot")
        print("  4. Create Predictor")
        print("  5. Create Custom AI")
        print("  6. List Created Models")
        print("  7. Install Dependencies")
        print("  8. Exit")
        print("")

    def create_model(self, model_type: str):
        """Create a new AI model"""
        model_name = input(f"Enter name for your {model_type}: ").strip()
        if not model_name:
            model_name = f"{model_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        model_dir = os.path.join(AI_MODELS_DIR, model_name)
        os.makedirs(model_dir, exist_ok=True)

        template_path = os.path.join(TEMPLATES_DIR, f"{model_type}.py")
        if not os.path.exists(template_path):
            print(f"Template not found: {template_path}")
            return

        model_path = os.path.join(model_dir, f"{model_name}.py")

        # Copy template
        with open(template_path, 'r') as f:
            template = f.read()

        with open(model_path, 'w') as f:
            f.write(template)

        # Create README
        readme_path = os.path.join(model_dir, "README.md")
        with open(readme_path, 'w') as f:
            f.write(f"# {model_name}\n\n")
            f.write(f"AI Model Type: {model_type}\n")
            f.write(f"Created: {datetime.now().isoformat()}\n\n")
            f.write("## Usage\n\n")
            f.write(f"```python\n")
            f.write(f"from {model_name} import *\n")
            f.write(f"# Your code here\n")
            f.write(f"```\n")

        print(f"\n✅ Model created: {model_name}")
        print(f"   Location: {model_dir}")
        print(f"   File: {model_path}")

        self.config["models_created"] += 1
        self.save_config()

        return model_path

    def list_models(self):
        """List created models"""
        if not os.path.exists(AI_MODELS_DIR):
            print("No models created yet.")
            return

        models = [d for d in os.listdir(AI_MODELS_DIR)
                  if os.path.isdir(os.path.join(AI_MODELS_DIR, d))]

        if not models:
            print("No models created yet.")
            return

        print(f"\n📊 Created Models ({len(models)}):")
        print("")
        for model in models:
            model_dir = os.path.join(AI_MODELS_DIR, model)
            files = os.listdir(model_dir)
            print(f"  • {model}")
            for file in files:
                print(f"    - {file}")
        print("")

    def install_dependencies(self):
        """Install required dependencies"""
        print("\n📦 Installing dependencies...")
        print("")

        dependencies = [
            "numpy",
            "scikit-learn",
            "tensorflow",  # Optional for image classifier
            "pillow"  # Optional for image processing
        ]

        for dep in dependencies:
            print(f"Installing {dep}...")
            try:
                subprocess.run([sys.executable, "-m", "pip", "install", dep],
                             check=True, capture_output=True)
                print(f"  ✅ {dep} installed")
            except subprocess.CalledProcessError as e:
                print(f"  ⚠️  {dep} installation failed: {e}")

        print("\n✅ Dependencies installation complete!")

    def run(self):
        """Run the AI Builder"""
        while True:
            self.show_menu()
            choice = input("Select option (1-8): ").strip()

            if choice == "1":
                self.create_model("text_classifier")
            elif choice == "2":
                self.create_model("image_classifier")
            elif choice == "3":
                self.create_model("chatbot")
            elif choice == "4":
                self.create_model("predictor")
            elif choice == "5":
                self.create_model("custom")
            elif choice == "6":
                self.list_models()
            elif choice == "7":
                self.install_dependencies()
            elif choice == "8":
                print("\n👋 Goodbye!")
                break
            else:
                print("\n⚠️  Invalid option. Please try again.")

# ============================================================================
# MAIN
# ============================================================================

def main():
    """Main function"""
    builder = AIBuilder()
    builder.run()

if __name__ == '__main__':
    main()
